///////////////////////////////////////////
// USER ROLES
// Define allowed user roles in the system
// Prevent invalid role values using union type
///////////////////////////////////////////
export type UserRole = "admin" | "barber" | "user";

///////////////////////////////////////////
// USER MODEL
// Represents complete user data from database
// Includes password for internal backend usage only
///////////////////////////////////////////
export interface User {
  id: number;
  name: string;
  email: string;
  password: string;
  role: UserRole;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

///////////////////////////////////////////
// USER RESPONSE
// Data returned to client
// Excludes sensitive password information
///////////////////////////////////////////
export interface UserResponse {
  id: number;
  name: string;
  email: string;
  role: UserRole;
  is_active: boolean;
  created_at: Date;
  updated_at: Date;
}

///////////////////////////////////////////
// CREATE USER INPUT
// Data required when creating a new user
// ID and timestamps are generated by database
///////////////////////////////////////////
export interface CreateUserInput {
  name: string;
  email: string;
  password: string;
  role: UserRole;
}

///////////////////////////////////////////
// UPDATE USER INPUT
// Fields allowed for user updates
// Supports partial updates with optional fields
///////////////////////////////////////////
export interface UpdateUserInput {
  name?: string;
  email?: string;
  password?: string;
  is_active?: boolean;
}
